import { notFound } from 'next/navigation';
import Link from 'next/link';
import type { Metadata } from 'next';
import { loadGraphData } from '@/lib/graph-data';

interface Props {
  params: Promise<{ genre: string }>;
}

// Only shoegaze is fully built in v1; others render a stub.
const BUILT_GENRES = new Set(['shoegaze']);

export function generateStaticParams() {
  const data = loadGraphData();
  return data.genres.map(g => ({ genre: g.id }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { genre } = await params;
  const data = loadGraphData();
  const g = data.genres.find(x => x.id === genre);
  if (!g) return {};
  return { title: `${g.name} — Starweave` };
}

export default async function GenrePage({ params }: Props) {
  const { genre } = await params;
  const data = loadGraphData();
  const genreData = data.genres.find(g => g.id === genre);
  if (!genreData) notFound();

  if (!BUILT_GENRES.has(genre)) {
    return (
      <div className="genre-stub">
        <p className="genre-stub__title">{genreData.name}</p>
        <p className="genre-stub__text">
          This genre story is coming in a future update. The graph already includes{' '}
          {genreData.name.toLowerCase()} artists — explore them on the{' '}
          <Link href="/" style={{ color: 'var(--color-shoegaze)' }}>graph</Link>.
        </p>
        <Link href="/" className="genre-page__graph-btn" style={{ display: 'inline-flex' }}>
          Open graph →
        </Link>
      </div>
    );
  }

  // --- Shoegaze story ---
  const shoegazeArtists = data.artists.filter(a =>
    a.genres.includes('shoegaze'),
  );
  const pioneers = shoegazeArtists.filter(a =>
    a.activeFrom && a.activeFrom < 1995,
  );
  const modern = shoegazeArtists.filter(a =>
    a.activeFrom && a.activeFrom >= 1995,
  );

  return (
    <article className="genre-page">
      <div className="ai-draft-notice">
        <span className="ai-draft-notice__icon" aria-hidden>⚠</span>
        <p className="ai-draft-notice__text">
          <strong>AI-drafted · pending review</strong> — The prose below was generated by an LLM as a
          first draft and has not been fact-checked by a human editor. Treat it as a starting point,
          not an authority. Influence edges on the graph are separately verified.
        </p>
      </div>

      <header className="genre-page__header">
        <p className="genre-page__super">Genre story</p>
        <h1 className="genre-page__title">Shoegaze</h1>
        <p className="genre-page__deck">
          Guitar-pedal haze, oceanic walls of distortion, and vocals buried so deep in the mix
          they become texture. Shoegaze emerged from the UK in the late 1980s as a reaction
          against the studied cool of post-punk — something more overwhelming, more ambiguous,
          harder to hold at arm&apos;s length.
        </p>
      </header>

      <section className="genre-page__section">
        <h2>Origin</h2>
        <p>
          The name came from a dismissive joke — these guitarists spent their live sets
          staring at their pedalboards, lost in the sound they were making. The Jesus and
          Mary Chain sparked the template in 1985 with <em>Psychocandy</em>: Velvet Underground
          drones run through walls of feedback, with melodies buried underneath.
        </p>
        <p>
          By 1988–1991 a cluster of Oxford and Reading acts — Ride, Slowdive, Chapterhouse —
          had formed around Creation and 4AD, the two labels that would define the genre&apos;s
          first wave. My Bloody Valentine&apos;s <em>Loveless</em> (1991) set a ceiling nobody
          has convincingly matched since.
        </p>
      </section>

      <section className="genre-page__section">
        <h2>Pioneers</h2>
        <p>
          These artists built the genre&apos;s first wave, most active between 1983 and 1995.
          Many were initially dismissed as derivative by the press and commercially
          overlooked — all are now considered essential.
        </p>
        <div className="genre-page__artist-list">
          {pioneers.map(a => (
            <Link key={a.id} href={`/artist/${a.id}`} className="genre-page__artist-chip">
              {a.name}
            </Link>
          ))}
        </div>
      </section>

      <section className="genre-page__section">
        <h2>Modern torchbearers</h2>
        <p>
          After a mid-90s backlash quieted the original wave, shoegaze never fully
          disappeared — it went underground and global. Artists like Deerhunter, Beach House,
          Wolf Alice, and Korea&apos;s Parannoul absorbed the template and pushed it forward,
          often in entirely different cultural contexts.
        </p>
        <div className="genre-page__artist-list">
          {modern.map(a => (
            <Link key={a.id} href={`/artist/${a.id}`} className="genre-page__artist-chip">
              {a.name}
            </Link>
          ))}
        </div>
      </section>

      <Link href="/" className="genre-page__graph-btn">
        View in graph →
      </Link>
    </article>
  );
}
