import { readFileSync } from 'fs';
import { resolve } from 'path';
import type { GraphData } from '@/data/types';

let _cache: GraphData | null = null;

// Server-only: reads public/graph.json generated by the build pipeline.
export function loadGraphData(): GraphData {
  if (_cache) return _cache;
  const filePath = resolve(process.cwd(), 'public', 'graph.json');
  const raw = readFileSync(filePath, 'utf-8');
  _cache = JSON.parse(raw) as GraphData;
  return _cache;
}
